name: Cypress Tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          ELECTRON_EXTRA_LAUNCH_ARGS: --remote-debugging-port=9222
        with:
          build: npm run build
          start: npm run preview
          browser: chrome

      - name: Run Cypress with Visual Tests
        run: |
          $(npm bin)/cypress run --config baseUrl=http://localhost:3000

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports

  manual-review:
    runs-on: ubuntu-latest
    needs: [cypress-run] # Run after Cypress run
    if: github.event_name == 'pull_request'
    steps:
      - name: Manual UI Review
        run: echo "UI Review pending approval..."
